#!/bin/sh
# Summary: Tell Safari to refresh the current tab.
#
# This reloads whatever is in Safari's front-most window or tab but doesn't
# switch focus to it.  This script is useful when used in conjunction with
# something like 'entr' or 'fswatch' to watch a file or directory.
#
# Copyright 2024 Michael Hucka.
# License: MIT License – see file "LICENSE" in the project website.
# Website: https://github.com/mhucka/mac-scripts

version_number="1.0.1"
website="https://github.com/mhucka/mac-scripts"

print_usage() {
cat <<EOF >&2
Usage:
    $program [options]

This takes no arguments.  When invoked, it tells Safari to reload whatever
is currently in its front-most tab or window.

Options:
    -h, --help          Print this help message and exit.
    -v, --version       Display the current version number and exit.

EOF
    print_version
}

print_version() {
    echo "Version: $program $version_number" 1>&2
    echo "Author:  Mike Hucka <mhucka@caltech.edu>" 1>&2
    echo "Website: $website" 1>&2
}

parse_args() {
    while [ $# -gt 0 ]; do
        case $1 in
            -h | --help )
                print_usage
                exit 0
                ;;
            -v | --version )
                print_version
                exit 0
                ;;
            *)
                print_usage
                exit 0
                ;;
        esac
        shift
    done
}

# JavaScript code originally from
# https://discussions.apple.com/message/24389284#24389284

reload_safari() {
    osascript <<EOF
tell application "Safari"
    tell window 1
        do JavaScript "window.location.reload(true)" in current tab
    end tell
end tell
EOF
}

#
# Main entry point.
#

program=${0##*/}
parse_args "$@"
reload_safari
