#!/bin/sh
#──────────────────────────────────────────────────────────────────────────────
# @file    interm
# @brief   Pause or continue Spotlight
# @author  Michael Hucka <mhucka@caltech.edu>
# @license Please see the file LICENSE in the project directory
# @website https://github.com/mhucka/mac-scripts
#──────────────────────────────────────────────────────────────────────────────

CMD="unload"
while [ $# -gt 0 ]; do
    case $1 in
        run )
            CMD="load"
            ;;
        pause )
            CMD="unload"
            ;;
    esac
    shift
done
sudo launchctl $CMD -w /System/Library/LaunchDaemons/com.apple.metadata.mds.plist
