#!/bin/sh
# Summary: Pause or continue Spotlight.
#
# Copyright (C) 2024 Michael Hucka.
# License: Modified BSD 3-Clause – see file "LICENSE" in the project website.
# Website: https://github.com/mhucka/mac-scripts

CMD="unload"
while [ $# -gt 0 ]; do
    case $1 in
        run )
            CMD="load"
            ;;
        pause )
            CMD="unload"
            ;;
    esac
    shift
done
sudo launchctl $CMD -w /System/Library/LaunchDaemons/com.apple.metadata.mds.plist
